spring.application.name=lab
axon.axonserver.enabled=false

# Main application DB (patients table)
spring.datasource.url=jdbc:mysql://localhost:3306/labdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=lab_user
spring.datasource.password=lab_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Separate Axon event store DB
eventstore.datasource.url=jdbc:mysql://localhost:3306/lab_events?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
eventstore.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
eventstore.datasource.username=lab_user
eventstore.datasource.password=lab_pass

# Use subscribing processor so TokenEntry is not required.
axon.eventhandling.processors.walter.example.lab.service.handler.mode=subscribing
